### ISSUE TITLE
DukLuv fails to compile using VS2015

### ISSUE THREAD

**Issue by fatcerberus** [creationix/dukluv#18]
I was unable to build dukluv from a fresh checkout using Visual Studio 2015.  After running CMake and opening the resulting solution file, I get the following syntax error when attempting to compile it:
```
4>c:\src\dukluv\src\duv.h(12): error C2059: syntax error: 'constant'
```

On this line:
```c
typedef enum { false, true } bool;
```

I believe VS2013 and later include C99 `bool` via stdint.h, so that's likely the cause of this.

**Comment by creationix** [comment]
Can I wrap this in an `#ifdef`?  I'm not sure how this is supposed to work.

Another idea is just to `#include <stdbool.h>` if we can assume it exists.

**Comment by fatcerberus** [comment]
I believe VS2013 and later includes `stdbool.h`.  I'd recommend:

```c
#if _MSC_VER >= 1800
#include <stdbool.h>
#else
typedef enum { false, true } bool;
#endif
```

**Comment by creationix** [comment]
Sounds good.  Did you want to send a PR?

**Comment by fatcerberus** [comment]
Sure. :)
