### ISSUE TITLE
Check if it need rt library.

### ISSUE THREAD

**Issue by aseaday** [creationix/dukluv#23]
I find a problem when build dukluv in different platform.
```
if("${CMAKE_SYSTEM_NAME}" MATCHES "Linux")
  target_link_libraries(duktape
    m dl
  )
endif()
```
It will met some problems when I need to build it with library rt. In unix like system and openwrt, you needn't to state the it needs librt. But in some platform like raspberry. It need it.

**Comment by creationix** [comment]
https://github.com/luvit/luvit/tree/master/deps
