### ISSUE TITLE
TCP Server fails with uncaught exception

### ISSUE THREAD

**Issue by FreshXOpenSource** [creationix/dukluv#27]
Taking the tcp-echo.js example and removing the line 

```//client = new Client("127.0.0.1", 1337);```

gives me a TCP echo server listening on Port 1337.

If i run now a telnet against this server, everything works fine.
If i run now a an automatic connection closing netcat with 

```echo Hello Server | nc -c localhost 1337```

against the server, it breaks down with
```
"server" [Server 0x7fce50501950]
"server.onconnection"
"socket" [ClientHandler 0x7fce50422cf0]
"server.accept" [ClientHandler 0x7fce50422cf0]
"socket.readStart"
"socket.onread" [Buffer 61 62 63 0a]
"socket.write" [Buffer 61 62 63 0a]

Uncaught Exception:

(null)
```

Any suggestions, what could be the reason? Thanks in advance!

**Comment by creationix** [comment]
It could be something being GCed too soon.  In async bindings, I have to be careful to add every callback on the list of GC roots somehow since typically nothing in the language references them after they are passed to an async function.

Without a backtrace, I can't really know what the cause is.

**Comment by FreshXOpenSource** [comment]
either you can reproduce it yourself using ```nc -c``` or can you let me know how i can provide you with a backtrace?

**Comment by creationix** [comment]
I'm afraid I don't have time to debug it myself today.  If you can compile it with debug symbols and run with gdb or lldb, then run the `bt` and `list` commands when it crashes.

**Comment by creationix** [comment]
Also strace output is sometimes helpful, you'll want to pipe stderr or stdout to a file so they aren't mixed together.

**Comment by FreshXOpenSource** [comment]
Its not really crashing, its exiting with 1, so no bt possible. i can get a strace by tomorrow only (on a mac right now)

```
Process 23738 launched: ./dukluv' (x86_64)
"server" [Server 0x100d09fa0]
"server.onconnection"
"socket" [ClientHandler 0x1019000f0]
"server.accept" [ClientHandler 0x1019000f0]
"socket.readStart"
"socket.onread" [Buffer 61 62 63 0a]
"socket.write" [Buffer 61 62 63 0a]

Uncaught Exception:

(null)

Process 23738 exited with status = 1 (0x00000001)
```

**Comment by creationix** [comment]
oh, then it's throwing a JS exception in a callback somewhere.  Try wrapping the body of the callback in try..catch and printing the error instead of throwing it.

**Comment by creationix** [comment]
but I see, the exception is null, that's strange.

**Comment by FreshXOpenSource** [comment]
i guess, netcat closes the connection too fast. the actual problem comes now though (i added a try/catch around the answer to the client). now when i run a loop of connections against the server its fails like this after the 3rd or 4th connection

```for i in `seq 1 100`; do nc -c localhost 1337; done```

results in 

```
"server" [Server 0x7fcf83c31f70]
"server.onconnection"
"socket" [ClientHandler 0x7fcf83c23400]
"server.accept" [ClientHandler 0x7fcf83c23400]
"socket.readStart"
"socket.onread" [Buffer 61 62 63 0a]
"socket.write" [Buffer 61 62 63 0a]
"socket.onread" [Error ECONNRESET: connection reset by peer]
"socket.write" [Error ECONNRESET: connection reset by peer]
ctx: top=3, stack=[|a08fc283cf7f0000c0b9a303010000000c000000000000000000000000000000d0b9a303010000000823c383cf7f000000000000000000000000000000000000000000000000000000000000000000000000000000000000646000000000000000000000000000004003990301000000d00199030100000000000000000000000000000000000000200ba2030100000008a2c283cf7f000008a2c283cf7f000018a2c283cf7f000018a2c283cf7f000001000000010000001500000000000000000000000000000040a2c283cf7f000040a2c283cf7f000050a2c283cf7f000050a2c283cf7f0000000000000000000000000000ffffffff00000000000000000000000000000000|,{},undefined]
"Error : TypeError: Invalid argument type for data"
"server.onconnection"
"socket" [ClientHandler 0x7fcf84800150]
"server.accept" [ClientHandler 0x7fcf84800150]
"socket.readStart"
"socket.onread" [Buffer 31 0a]
"socket.write" [Buffer 31 0a]
"socket.onread" [Error ECONNRESET: connection reset by peer]
"socket.write" [Error ECONNRESET: connection reset by peer]
ctx: top=3, stack=[|a0008084cf7f0000c0b9a303010000000c000000000000000000000000000000d0b9a3030100000098a1c283cf7f000000000000000000000000000000000000000000000000000000000000000000000000000000000000646000000000000000000000000000004003990301000000d00199030100000000000000000000000000000000000000200ba20301000000280a8084cf7f0000280a8084cf7f0000380a8084cf7f0000380a8084cf7f0000010000000100000016000000000000000000000000000000600a8084cf7f0000600a8084cf7f0000700a8084cf7f0000700a8084cf7f0000000000000000000000000000ffffffff00000000000000000000000000000000|,{},undefined]
"Error : TypeError: Invalid argument type for data"
"server.onconnection"
"socket" [ClientHandler 0x7fcf84800110]
"server.accept" [ClientHandler 0x7fcf84800110]
"socket.readStart"
"socket.onread" [Buffer 32 0a]
"socket.write" [Buffer 32 0a]
"socket.onread" [Error ECONNRESET: connection reset by peer]
"socket.write" [Error ECONNRESET: connection reset by peer]
ctx: top=3, stack=[|50158084cf7f0000c0b9a303010000000c000000000000000000000000000000d0b9a30301000000b8098084cf7f000000000000000000000000000000000000000000000000000000000000000000000000000000000000646000000000000000000000000000004003990301000000d00199030100000000000000000000000000000000000000200ba20301000000a8198084cf7f0000a8198084cf7f0000b8198084cf7f0000b8198084cf7f0000010000000100000017000000000000000000000000000000e0198084cf7f0000e0198084cf7f0000f0198084cf7f0000f0198084cf7f0000000000000000000000000000ffffffff00000000000000000000000000000000|,{},undefined]
"Error : TypeError: Invalid argument type for data"
"server.onconnection"
"socket" [ClientHandler 0x7fcf84800360]
"server.accept" [ClientHandler 0x7fcf84800360]
"socket.readStart"
"socket.onread" [Buffer 33 0a]
"socket.write" [Buffer 33 0a]

Uncaught Exception:

Error: invalid stack index -3
	duk_api_stack.c:302
	anon  native strict preventsyield
```

**Comment by FreshXOpenSource** [comment]
This currently prevents me from using it as a generic TCP server in our project ...

**Comment by creationix** [comment]
Ouch, that looks like a nasty bug.  I'll try to remember to look at this tonight after work.  
@svaarala if you have time and interest I'm sure you could track this down as well.

**Comment by FreshXOpenSource** [comment]
do you need my current tcp-echo.js ?

**Comment by creationix** [comment]
You can include it just to be explicit.  I thought the original message would be enough to reproduce it locally.

**Comment by FreshXOpenSource** [comment]
Thanks for your effort! Sorry here the right netcat call 

```for i in `seq 1 100`; do echo $i | nc -c localhost 1337; done```

**Comment by FreshXOpenSource** [comment]
```
"use strict";
var p = require('./modules/utils.js').prettyPrint;
var Tcp = require('./modules/classes.js').Tcp;

var server, socket, client;

function Server(host, port) {
  Tcp.call(this);
  p("server", this);
  this.bind(host, port);
  this.listen(128, this.onConnection);
}
Server.prototype.__proto__ = Tcp.prototype;
Server.prototype.onConnection = function onConnection(err) {
  assert(this === server);
  if (err) { throw err; }
  p("server.onconnection");
  socket = new ClientHandler(this);
  p("server.accept", socket);
  this.accept(socket);
  p("socket.readStart");
  socket.readStart(socket.onRead);
};

function ClientHandler(server) {
  Tcp.call(this);
  p("socket", this);
  this.server = server;
}
ClientHandler.prototype.__proto__ = Tcp.prototype;
ClientHandler.prototype.onRead = function onRead(err, data) {
  assert(this === socket);
  try {
 //   if (err) { throw err; }
    p("socket.onread", data);
    if (data) {
      p("socket.write", data);
      this.write(data);
    }
    else {
      p("socket.shutdown");
      this.shutdown();
      p("socket.readStop");
      this.readStop();
    }
  }catch(err){
    p("Error : "+err);
  }
};

server = new Server("127.0.0.1", 1337);

function assert(cond, message) {
  if (!cond) {
    throw new Error(message || "Assertion Failure");
  }
}
```

**Comment by svaarala** [comment]
@FreshXOpenSource Just quickly testing that I can't reproduce this on Ubuntu 14.04 (instead `nc -c` I had to use `nc -q 0` though, so it's a different netcat).

Maybe unrelated, but after ~1000 connections the server won't accept any more connections.

**Comment by FreshXOpenSource** [comment]
on linux (centos 7 x86_x64) i can confirm this (i use nmap-netcat with parameter -w 1 here ...), no stack index failure, but after ~1009 connections the server becomes unusable and directly terminates the connection request

# telnet localhost 1337
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.

@svaarala : i had the same issue on my own uv_ server implementation. its two things 
a.) ulimit -n is 1024 so after 1024 open files (connections) you dont get any further, set it to 4096 and u can go on
b.) on my implementation i did not close the socket correctly thus having the open files increasing

**Comment by FreshXOpenSource** [comment]
regarding the other issue (on osx yosemite) i will go on investigating if its a netcat issue or an OSX issue and report back

**Comment by FreshXOpenSource** [comment]
i can not reproduce the problem with a "clean" tcp client such as telnet, nmap-ncat etc ... only the netcat 0.7.1 implementation seems to produce the problem with an unclean shutdown of the socket.

if the socket gets closed correctly after readStop (missing in the code example above), the ulimit of opened files is also not reached.

i guess you can close the issue, thanks for your help!

**Comment by svaarala** [comment]
Because it happens with an unclean shutdown, is it possible this would be a SIGPIPE issue in libuv?

**Comment by creationix** [comment]
I don't remember if I ever added sigpipe handling in dukluv.  It's not automatic in libuv itself.

**Comment by svaarala** [comment]
One can add SIGPIPE handler and/or make every socket explicitly avoid causing a SIGPIPE. The latter is unfortunately platform specific. Maybe this would deserve a separate open issue (at least to check the handling)?

**Comment by svaarala** [comment]
Incidentally, SIGPIPE is one "fun" UNIX feature. But it pales in comparison to handling EINTR correctly ;)

**Comment by mamod** [comment]
I could reproduce this on windows as well using win32 netcat port, telnet works just fine, so maybe this is not a SIGPIPE issue!!
