### ISSUE TITLE
Binary download

### ISSUE THREAD

**Issue by denisdemaisbr** [creationix/dukluv#30]
Hi, its possible release a final binary?

I'm using cygwin and fail on generate executable.

thanks

**Comment by creationix** [comment]
Sorry, this project is not stable yet on windows.  It's too early to start releasing binaries.

**Comment by avih** [comment]
In my little testing (not recently, but my patches are still the latest at the repo), I think it was reasonably stable.

I can post a win32 binary from current HEAD (f02103b) if you're OK with it - @creationix . Shall I?

**Comment by avih** [comment]
(@creationix agreed on IRC).

@denisdemaisbr I've created a win32 binary build from current git master. You can get it here https://github.com/avih/dukluv/releases/tag/SNAPSHOT-2016-10-06

**Comment by denisdemaisbr** [comment]
thanks!

**Comment by creationix** [comment]
Thanks @avih.
