### ISSUE TITLE
Integer-to-NULL comparison in dukluv/fs.c

### ISSUE THREAD

**Issue by darkuranium** [creationix/dukluv#6]
It would appear that the `dukluv/fs.c` file contains a integer-to-NULL comparison in line 61: https://github.com/creationix/dukluv/blob/master/src/fs.c#L61

    static int duv_string_to_flags(duk_context *ctx, const char* string) {
        bool read = false;
        bool write = false;
        int flags = 0;
        while (string && string[0] != NULL) { //< line 61
            switch (string[0]) {

Type of `string[0]` is `char`, but it is being compared with `NULL` (which is used for pointers, and may be `(void*)0` in some compilers).

There maybe similar problems elsewhere, but I didn't check. Compiling with `-Wall` in GCC or CLang should emit a warning about this.

**Comment by creationix** [comment]
Indeed, It appears I wasn't clear in my preference for the PR, I've changed it to be a simple truthy test. The logic is to loop till null byte is found which is char 0.

https://github.com/creationix/dukluv/commit/08f96b53f0529fadf8346f0a7a56cbc892efa8ce
