### ISSUE TITLE
Bug with absolute filepath in argument 

### ISSUE THREAD

**Issue by tberthe** [creationix/dukluv#8]
Calling DukLuv with an absolute filepath give me this error:

```
~/ $ ~/dukluv/build/dukluv /tmp/test.js

Uncaught Exception:

Error: ENOENT: no such file or directory: /home/tberthe/tmp/test.js
        /home/tberthe/dukluv/src/main.c:32
        anon  native strict preventsyield
        anon  native strict preventsyield
        anon  native strict preventsyield
        anon  native strict preventsyield
```

**Comment by creationix** [comment]
Looks like the fix needs to go here https://github.com/creationix/dukluv/blob/49a222c9bc9e1442ff627b8398ea1378e31de714/src/main.c#L66

It needs to check if any of the inputs start with a slash and ignore all pieces before that.

Perhaps the fastest technique would be to walk the initial list of strings backwards and stop at the first one starting with a `/`.

I'll see if I can implement this later.
